# Numpy

In [35]:
import numpy as np

## 1 task

In [36]:
a = np.array([[1,6],[2.,8],[3,11],[3,10],[1,7]])
print(a)
a.shape

[[ 1.  6.]
 [ 2.  8.]
 [ 3. 11.]
 [ 3. 10.]
 [ 1.  7.]]


(5, 2)

In [37]:
mean_a = a.mean(axis=0)
mean_a

array([2. , 8.4])

## 2 task

In [38]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

## 3 task

In [39]:
a_centered_sp = a_centered[:,0].dot(a_centered[:,1])
a_centered_sp / (a_centered.shape[0] - 1)

2.0

## 4 task

In [40]:
print(np.cov(a.T)[0,1])
np.cov(a.T)[0,1] == a_centered_sp / (a_centered.shape[0] - 1)

2.0


True

# Pandas

In [41]:
import pandas as pd

## 1 task

In [42]:
authors = pd.DataFrame({"author_id": [1,2,3], 
                        "author_name": ['Тургенев', 'Чехов','Островский']})
authors  

author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский

In [43]:
# Цены на книги не нашел. Решил их придумать сам.
book = pd.DataFrame({"author_id": [1, 1, 1, 2, 2, 3, 3],
                      "book_title": ['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
                      "price": [100, 200, 150, 300, 50, 120, 230]
})
book 

author_id            book_title  price
0          1           Отцы и дети    100
1          1                 Рудин    200
2          1     Дворянское гнездо    150
3          2      Толстый и тонкий    300
4          2       Дама с собачкой     50
5          3                 Гроза    120
6          3  Таланты и поклонники    230

## 2 task

In [44]:
author_price = pd.merge(authors, book, on = 'author_id', how= 'inner')
author_price

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    100
1          1    Тургенев                 Рудин    200
2          1    Тургенев     Дворянское гнездо    150
3          2       Чехов      Толстый и тонкий    300
4          2       Чехов       Дама с собачкой     50
5          3  Островский                 Гроза    120
6          3  Островский  Таланты и поклонники    230

## 3 task

In [45]:
top5 = author_price.sort_values(by = "price").tail()
top5

author_id author_name            book_title  price
5          3  Островский                 Гроза    120
2          1    Тургенев     Дворянское гнездо    150
1          1    Тургенев                 Рудин    200
6          3  Островский  Таланты и поклонники    230
3          2       Чехов      Толстый и тонкий    300

## 4 task

In [46]:
gb_author_price = author_price.groupby("author_id")
authors_stat = pd.DataFrame({
    "author_name": gb_author_price["author_name"].unique().apply(lambda x: x[0]),
    "min_price": gb_author_price["price"].min(),
    "max_price": gb_author_price["price"].max(),
    "mean_price": gb_author_price["price"].mean()
})
authors_stat

author_name  min_price  max_price  mean_price
author_id                                              
1            Тургенев        100        200       150.0
2               Чехов         50        300       175.0
3          Островский        120        230       175.0

## 5 task

In [47]:
author_price["cover"] = ['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая']
author_price

author_id author_name            book_title  price    cover
0          1    Тургенев           Отцы и дети    100  твердая
1          1    Тургенев                 Рудин    200   мягкая
2          1    Тургенев     Дворянское гнездо    150   мягкая
3          2       Чехов      Толстый и тонкий    300  твердая
4          2       Чехов       Дама с собачкой     50  твердая
5          3  Островский                 Гроза    120   мягкая
6          3  Островский  Таланты и поклонники    230   мягкая

In [48]:
?pd.pivot_table

In [50]:
book_info = pd.pivot_table(author_price, values="price", index="author_name", columns=["cover"], aggfunc=np.sum, fill_value=0)
book_info

cover        мягкая  твердая
author_name                 
Островский      350        0
Тургенев        350      100
Чехов             0      350

In [57]:
book_info.to_pickle("book_info.pkl")
book_info2 = pd.read_pickle("book_info.pkl")
print(book_info2, "\n")
book_info == book_info2

cover        мягкая  твердая
author_name                 
Островский      350        0
Тургенев        350      100
Чехов             0      350 



cover        мягкая  твердая
author_name                 
Островский     True     True
Тургенев       True     True
Чехов          True     True